name: CI

on:
    push:
      branches:
        - 'main'
    pull_request:
      branches:
        - 'main'

    # Allow manually triggering of the workflow.
    workflow_dispatch: {}

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Restore dependencies
      run: nuget restore

    - name: Build
      run: dotnet build --no-restore --configuration Release
