name: CI

on:
    push:
      branches:
        - 'main'
    pull_request:
      branches:
        - 'main'

    # Allow manually triggering of the workflow.
    workflow_dispatch: {}

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        runtime: [win-x64, linux-x64, linux-arm64, linux-arm, osx-x64, osx-arm64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Restore dependencies
      run: nuget restore

    - name: Build Debug
      run: dotnet build --no-restore --configuration Debug

    - name: Build Release
      run: ./publish/publish.ps1 -Runtimes ${{ matrix.runtime }} -Version "0.0.0"
